Fix build error due to babel/babel-loader mismatch.
Error message:

> Module build failed: Error: Cannot find module '@babel/core'
  babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd
  like to use Babel 6.x ('babel-core'), you sh ould install
  'babel-loader@7'.

I've reverted to babel-loader@7 as the more conservative change.